backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("rosetta/", include("rosetta.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("api/payments/", include("payments.urls")),
    path("api/accounts/", include("accounts.api.urls")),
    path("api/", include("core.api.urls")),
    path("api/auth/", include("authentication.urls")),
    path("facebook/", include("facebook.urls")),
    path("api/ai-assistant/", include("ai_assistant.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("api/logs/", include("logs_observation.urls")),
    path("api/notifications/", include("notifications.urls")),
    path("subscriptions/", include("subscriptions.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

core/api/urls.py
from django.urls import path

from core.api.views import (
    GetFrequentlyAskedQuestionsListView,
    HistoryAPIView,
    ProductsListView,
    UpcomingAPIView,
    set_timezone,
)

app_name = "core_api"
urlpatterns = [
    path("products/", ProductsListView.as_view(), name="products-list"),
    path(
        "frequently-asked-questions/",
        GetFrequentlyAskedQuestionsListView.as_view(),
        name="faq-api",
    ),
    path(
        "history/paginated-predictions/",
        HistoryAPIView.as_view(),
        name="paginated-predictions-history",
    ),
    path(
        "upcoming/",
        UpcomingAPIView.as_view(),
        name="upcoming-predictions-tickets",
    ),
    path("set-timezone/", set_timezone, name="set_timezone"),
]

core/urls.py
from django.urls import path

from .views import (
    AboutUsView,
    AiAssistantView,
    ContactUsView,
    CookiesPolicyView,
    DetailedPredictionView,
    DisclaimerView,
    FaqView,
    HistoryView,
    HomeView,
    HowToJoinView,
    PrivacyPolicyView,
    ReferralTelegramLandingView,
    SubscriptionRequiredView,
    TelegramLandingView,
    TermsOfServiceView,
    UpcomingMatchesView,
    VerifyEmailView,
)

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("history/", HistoryView.as_view(), name="history"),
    path("frequently-asked-questions/", FaqView.as_view(), name="faq"),
    path("how-to-join/", HowToJoinView.as_view(), name="how_to_join"),
    path("about-us/", AboutUsView.as_view(), name="about_us"),
    path("support/", ContactUsView.as_view(), name="contact_us"),
    path("disclaimer/", DisclaimerView.as_view(), name="disclaimer"),
    path("terms-of-service/", TermsOfServiceView.as_view(), name="terms_of_service"),
    path("privacy-policy/", PrivacyPolicyView.as_view(), name="privacy_policy"),
    path("cookies-policy/", CookiesPolicyView.as_view(), name="cookies_policy"),
    path("upcoming-matches/", UpcomingMatchesView.as_view(), name="upcoming_matches"),
    path(
        "subscription-required/",
        SubscriptionRequiredView.as_view(),
        name="subscription_required",
    ),
    path("verify-email/", VerifyEmailView.as_view(), name="verify_email"),
    path(
        "predictions/<int:pk>/",
        DetailedPredictionView.as_view(),
        name="detailed_prediction",
    ),
    path("ai-assistant/", AiAssistantView.as_view(), name="ai_assistant"),
    path("start/", TelegramLandingView.as_view(), name="telegram_landing"),
    path(
        "begin/", ReferralTelegramLandingView.as_view(), name="telegram_landing_begin"
    ),
]

payments/urls.py
from django.urls import include, path

from payments.nviews import (
    CreateDailyOfferCheckoutUrl,
    CreatePredictionCheckoutUrl,
    CreateTicketCheckoutUrl,
    ManageSubscriptionView,
    PurchasePaymentSuccessView,
    SubscriptionPaymentSuccessView,
    VerifyMobilePurchaseView,
)
from payments.views.checkout import (
    CreateSubscriptionCheckoutUrl,
    UpdateSubscriptionView,
)
from payments.views.stripe_webhook import stripe_webhook

app_name = "payments"
urlpatterns = [
    path("checkout/", CreateSubscriptionCheckoutUrl.as_view(), name="checkout"),
    path(
        "prediction/checkout/<int:prediction_id>/",
        CreatePredictionCheckoutUrl.as_view(),
        name="prediction_checkout",
    ),
    path(
        "daily-offer/checkout/",
        CreateDailyOfferCheckoutUrl.as_view(),
        name="daily_offer_checkout",
    ),
    path(
        "ticket/checkout/<int:ticket_id>/",
        CreateTicketCheckoutUrl.as_view(),
        name="ticket_checkout",
    ),
    path(
        "manage-subscription/",
        ManageSubscriptionView.as_view(),
        name="manage_subscription",
    ),
    path(
        "update-subscription/",
        UpdateSubscriptionView.as_view(),
        name="update_subscription",
    ),
    path(
        "payment-success/",
        SubscriptionPaymentSuccessView.as_view(),
        name="payment_success",
    ),
    path(
        "payment/prediction/success/<int:prediction_pk>/",
        PurchasePaymentSuccessView.as_view(),
        name="purchase_payment_success",
    ),
    path("stripe/webhook/", stripe_webhook, name="stripe_webhook"),
    path(
        "mobile/verify-purchase/",
        VerifyMobilePurchaseView.as_view(),
        name="verify_mobile_purchase",
    ),
    path("revenuecat/", include("payments.mobile.urls")),
]

subscriptions/urls.py
from django.urls import path

from subscriptions.views import PlansView

app_name = "subscriptions"
urlpatterns = [
    path("plans/", PlansView.as_view(), name="plans"),
]

core/models.py
from datetime import timedelta
from decimal import Decimal

from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_ckeditor_5.fields import CKEditor5Field
from model_utils import FieldTracker
from solo.models import SingletonModel

from core.utils import BaseInternalModel
from subscriptions.models import Product

# Create your models here.


class BaseProductModel(BaseInternalModel):
    stripe_product_id = models.CharField(max_length=255)
    monthly_price = models.DecimalField(max_digits=10, decimal_places=2)
    monthly_price_stripe_id = models.CharField(max_length=255)
    monthly_switzerland_price_stripe_id = models.CharField(max_length=255)

    discounted_monthly_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    discounted_monthly_price_stripe_id = models.CharField(
        max_length=255, blank=True, null=True
    )
    discounted_switzerland_monthly_price_stripe_id = models.CharField(
        max_length=255, blank=True, null=True
    )

    yearly_price = models.DecimalField(max_digits=10, decimal_places=2)
    yearly_price_stripe_id = models.CharField(max_length=255)
    yearly_switzerland_price_stripe_id = models.CharField(max_length=255)
    discounted_yearly_price = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True
    )
    discounted_yearly_price_stripe_id = models.CharField(
        max_length=255, blank=True, null=True
    )
    discounted_switzerland_yearly_price_stripe_id = models.CharField(
        max_length=255, blank=True, null=True
    )
    mobile_product_id = models.CharField(max_length=255, blank=True, null=True)

    order = models.PositiveIntegerField(default=0)

    class Meta:
        abstract = True
        ordering = ["order"]


class FrequentlyAskedQuestion(BaseInternalModel):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    order = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ["order"]


class SiteSettings(BaseInternalModel, SingletonModel):
    customer_withdrawal_request_template_id = models.IntegerField(blank=True, null=True)
    email_confirmation_template_id = models.IntegerField(blank=True, null=True)
    password_reset_template_id = models.IntegerField(blank=True, null=True)
    generic_content_template_id = models.IntegerField(blank=True, null=True)
    notification_email = models.EmailField()

    def __str__(self):
        return "Site Settings"

    class Meta:
        verbose_name = "Site Settings"
        verbose_name_plural = "Site Settings"


class ApiSportModel(BaseInternalModel):
    class SportType(models.TextChoices):
        SOCCER = "SOCCER", _("Soccer")
        BASKETBALL = "BASKETBALL", _("Basketball")
        NFL = "NFL", _("NFL")
        NHL = "NHL", _("NHL")
        TEMP_FIX = "TEMP_FIX", _("Temporary Fix")

    product = models.ForeignKey(
        "subscriptions.Product", on_delete=models.SET_NULL, null=True
    )
    external_id = models.IntegerField(db_index=True)
    type = models.CharField(choices=SportType, max_length=255)

    def __str__(self):
        return f"{self.product.name} - {self.type}"

    class Meta:
        abstract = True
        unique_together = (
            "external_id",
            "type",
        )


class SportCountry(BaseInternalModel):
    name = models.CharField(max_length=255, unique=True)
    code = models.CharField(max_length=255, blank=True)
    logo = models.FileField(upload_to="assets/countries/flags/")

    def __str__(self):
        return self.name


class SportLeague(ApiSportModel):
    product = models.ForeignKey(
        "subscriptions.Product", on_delete=models.SET_NULL, null=True
    )
    external_id = models.IntegerField(db_index=True)
    name = models.CharField(max_length=255)
    friendly_name = models.CharField(max_length=255, blank=True, null=True)
    country = models.ForeignKey(SportCountry, on_delete=models.CASCADE)
    league_type = models.CharField(max_length=255)
    logo = models.FileField(upload_to="assets/leagues/logos/")
    current_season_year = models.IntegerField(blank=True, null=True, db_index=True)
    api_coverage_data = models.JSONField(null=True, blank=True)
    teams = models.ManyToManyField(
        "SportTeam", through="SportLeagueTeam", related_name="leagues"
    )

    @property
    def readable_name(self):
        if not self.friendly_name:
            return self.name

        return self.friendly_name

    def __str__(self):
        return self.name


class SportTeam(ApiSportModel):
    product = models.ForeignKey(
        "subscriptions.Product", on_delete=models.SET_NULL, null=True
    )
    external_id = models.IntegerField(db_index=True)
    name = models.CharField(max_length=255, db_index=True)
    logo = models.FileField(upload_to="assets/teams/logos/")

    @property
    def leagues_list(self):
        return list(self.leagues.all())

    def __str__(self):
        return f"{self.name}"


class TeamStanding(BaseInternalModel):
    league_team = models.OneToOneField(
        "SportLeagueTeam",
        on_delete=models.CASCADE,
        related_name="standings",
        primary_key=True,
    )
    data = models.JSONField(null=True, blank=True)


class SportLeagueTeam(models.Model):
    league = models.ForeignKey(
        SportLeague, on_delete=models.CASCADE, related_name="league_teams"
    )
    team = models.ForeignKey(
        SportTeam, on_delete=models.CASCADE, related_name="team_leagues"
    )
    season = models.IntegerField(db_index=True)

    class Meta:
        unique_together = [("league", "team", "season")]

    def __str__(self):
        return f"{self.team} in {self.league} ({self.season})"


class SportMatch(ApiSportModel):
    class Status(models.TextChoices):
        SCHEDULED = "SCHEDULED", _("Scheduled")
        IN_PROGRESS = "IN_PROGRESS", _("In Progress")
        FINISHED = "FINISHED", _("Finished")

    status = models.CharField(max_length=12, choices=Status.choices, db_index=True)
    product = models.ForeignKey(
        "subscriptions.Product", on_delete=models.SET_NULL, null=True
    )
    external_id = models.IntegerField(db_index=True)
    league = models.ForeignKey(SportLeague, on_delete=models.CASCADE)
    home_team = models.ForeignKey(
        SportTeam, on_delete=models.CASCADE, related_name="home_team"
    )
    home_team_score = models.CharField(blank=True)
    away_team = models.ForeignKey(
        SportTeam, on_delete=models.CASCADE, related_name="away_team"
    )
    away_team_score = models.CharField(blank=True)
    kickoff_datetime = models.DateTimeField(db_index=True)
    metadata = models.JSONField(null=True, blank=True)

    @property
    def is_live(self):
        # calculate if the match is live (soccer match)
        return (
            self.kickoff_datetime
            <= timezone.now()
            <= (self.kickoff_datetime + timedelta(minutes=105))
        )

    @property
    def league_name(self):
        return self.league.name

    def __str__(self):
        return f"[{self.league.name}] {self.home_team.name} vs {self.away_team.name} ({self.kickoff_datetime})"


class Prediction(BaseInternalModel):
    class Status(models.TextChoices):
        WON = "WON", _("Won")
        LOST = "LOST", _("Lost")
        PENDING = "PENDING", _("Pending")

    class Visibility(models.TextChoices):
        PUBLIC = "PUBLIC", "Public"
        PRIVATE = "PRIVATE", "Private"
        ADMIN = "ADMIN", "Admin Only"

    product = models.ForeignKey(
        "subscriptions.Product", on_delete=models.SET_NULL, null=True
    )
    visibility = models.CharField(
        max_length=10, choices=Visibility, default=Visibility.PUBLIC, db_index=True
    )
    match = models.OneToOneField(
        SportMatch, on_delete=models.CASCADE, unique=True, related_name="predictions"
    )
    prediction = models.CharField(max_length=255)
    odds = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(
        max_length=10, choices=Status, default=Status.PENDING, db_index=True
    )
    detailed_analysis = CKEditor5Field(blank=True)
    stake = models.DecimalField(
        max_digits=10, decimal_places=2, default=0.00, blank=True
    )
    tracker = FieldTracker()

    @property
    def can_view_stake(self):
        return self.status == Prediction.Status.PENDING and self.stake > 0

    @property
    def formatted_stake(self):
        if self.stake is None:
            return None

        stake = Decimal(self.stake).quantize(Decimal("0.01"))  # round to 2 decimals
        # Convert to string while removing trailing zeros
        normalized = stake.normalize()

        # If it's an integer (like 5.0), return as int
        if normalized == normalized.to_integral():
            return str(int(normalized))

        # If it has exactly 1 decimal place (like 5.50 -> 5.5), keep 1 decimal
        s = format(normalized, "f")
        if "." in s and len(s.split(".")[1]) == 1:
            return s

        # Otherwise, keep up to 2 decimals (like 10.25)
        return f"{stake:.2f}".rstrip("0").rstrip(".")

    @property
    def is_sport_prediction(self):
        return self.product.name == Product.Names.SOCCER

    @property
    def result(self):
        return f"{self.match.home_team_score} - {self.match.away_team_score}"

    @property
    def has_detailed_analysis(self):
        return (
            self.detailed_analysis != "" and self.detailed_analysis != "<p>&nbsp;</p>"
        )

    def __str__(self):
        return f"[{self.product.name}] {self.match.home_team.name} vs {self.match.away_team.name} ({self.prediction})"

    class Meta:
        verbose_name = "Prediction"
        verbose_name_plural = "Predictions"


class PickOfTheDay(BaseInternalModel, SingletonModel):
    prediction = models.OneToOneField(

core/templates/core/includes/footer.html
{% load static i18n %}
<footer class="bg-gradient-to-b from-primary-900 to-primary-950 pt-20 pb-10 relative overflow-hidden">
    <div class="absolute inset-0 bg-squares-pattern opacity-5 pointer-events-none"></div>

    <div class="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-secondary-500/50 to-transparent"></div>
    <div class="container mx-auto px-4">
        <div class="grid md:grid-cols-4 gap-12 mb-16">
            <div class="md:col-span-2">
                <img src="{% static 'assets/images/smore-app-icon--no-background.png' %}" alt="smoreltd.com"
                     class="h-12 mb-8">
                <p class="text-primary-300 max-w-md mb-8 text-lg leading-relaxed">{% trans "Expert sports predictions powered  by advanced analytics and professional insights. Join thousands of successful bettors who trust" %}
                    <span class="text-secondary-400">Smore</span>.</p>
                <div class="flex space-x-6"><a href="https://wa.me/+359884108275" target="_blank"
                                               rel="noopener noreferrer"
                                               class="bg-primary-800/50 p-3 rounded-lg hover:bg-secondary-500/10 hover:text-secondary-500 transition-all duration-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-message-circle w-5 h-5">
                        <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"></path>
                    </svg>
                </a><a href="https://t.me/smoreltd" target="_blank" rel="noopener noreferrer"
                       class="bg-primary-800/50 p-3 rounded-lg hover:bg-secondary-500/10 hover:text-secondary-500 transition-all duration-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-send w-5 h-5">
                        <path d="m22 2-7 20-4-9-9-4Z"></path>
                        <path d="M22 2 11 13"></path>
                    </svg>
                </a><a href="https://facebook.com/smoreltd" target="_blank" rel="noopener noreferrer"
                       class="bg-primary-800/50 p-3 rounded-lg hover:bg-secondary-500/10 hover:text-secondary-500 transition-all duration-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-facebook w-5 h-5">
                        <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                    </svg>
                </a><a href="https://instagram.com/smoreltd" target="_blank" rel="noopener noreferrer"
                       class="bg-primary-800/50 p-3 rounded-lg hover:bg-secondary-500/10 hover:text-secondary-500 transition-all duration-300">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                         class="lucide lucide-instagram w-5 h-5">
                        <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                        <line x1="17.5" x2="17.51" y1="6.5" y2="6.5"></line>
                    </svg>
                </a></div>
            </div>
            <div>
                <h3 class="text-white font-semibold text-lg mb-6">{% trans "Quick Links" %}</h3>
                <ul class="space-y-4">
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:about_us' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "About Us" %}
                        </a>
                    </li>
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'subscriptions:plans' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "Plans" %}
                        </a>
                    </li>
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:contact_us' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "Contact" %}</a>
                    </li>
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:how_to_join' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "How to Join" %}</a>
                    </li>
                </ul>
            </div>
            <div><h3 class="text-white font-semibold text-lg mb-6">{% trans "Legal" %}</h3>
                <ul class="space-y-4">
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:terms_of_service' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "Terms of Service" %}</a>
                    </li>
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:privacy_policy' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "Privacy Policy" %}</a>
                    </li>
                    <li>
                        <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 flex items-center group"
                           href="{% url 'core:disclaimer' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                 stroke-linejoin="round"
                                 class="lucide lucide-chevron-right w-4 h-4 mr-2 text-secondary-500 transform group-hover:translate-x-1 transition-transform duration-300">
                                <path d="m9 18 6-6-6-6"></path>
                            </svg>
                            {% trans "Disclaimer" %}</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="border-t border-primary-800/50 pt-8">
            <div class="flex flex-col md:flex-row justify-between items-center">
                <p class="text-primary-400 text-sm mb-4 md:mb-0 tracking-wide">© {% now "Y" %}
                    Smore. {% trans "All rights reserved" %}.</p>
                <div class="flex items-center">
                    <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 text-sm px-4"
                       href="{% url 'core:terms_of_service' %}">{% trans "Terms" %}</a>
                    <div class=" w-1 h-1 rounded-full bg-primary-700">
                    </div>
                    <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 text-sm px-4"
                       href="{% url 'core:privacy_policy' %}">{% trans "Privacy" %}</a>
                    <div class=" w-1 h-1 rounded-full bg-primary-700">
                    </div>
                    <a class="text-primary-400 hover:text-secondary-400 transition-all duration-300 text-sm px-4"
                       href="{% url 'core:cookies_policy' %}">{% trans "Cookies" %}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

core/templates/core/includes/history_list.html
{% load i18n %}

{# 1. Loop through the objects #}
{% for item in object_list %}
    {% if item.type == 'prediction' %}
        {% with prediction=item.object %}
            {% include 'core/includes/prediction.html' with prediction=prediction %}
        {% endwith %}
    {% elif item.type == 'ticket' %}
        {% with ticket=item.object %}
            {% include 'core/includes/ticket.html' with ticket=ticket %}
        {% endwith %}
    {% endif %}
{% endfor %}

{# 2. The Load More Button (Only renders if there is a next page) #}
{% if page_obj.has_next %}
    <div id="load-more-target" class="col-span-full text-center mt-12">

        <button hx-get="{% url 'core:history' %}?page={{ page_obj.next_page_number }}&filter={{ request.GET.filter|default:'' }}&obj={{ request.GET.obj|default:'' }}"
                hx-trigger="click"
                hx-target="#load-more-target"
                hx-swap="outerHTML"
                class="group relative inline-flex items-center justify-center px-8 py-4 font-medium text-white bg-gradient-to-r from-secondary-600 to-secondary-500 rounded-lg overflow-hidden transition-all duration-300 hover:scale-105 hover:shadow-xl hover:shadow-secondary-600/30 w-48">

            <div class="absolute inset-0 bg-gradient-to-r from-secondary-400 to-secondary-300 opacity-0 group-hover:opacity-20 transition-opacity duration-300"></div>

            <div class="load-text relative flex items-center transition-opacity duration-200">
                <span class="text-lg">{% trans "Load More" %}</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                     fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                     class="lucide lucide-chevron-down w-5 h-5 ml-2 transform group-hover:translate-y-0.5 transition-transform duration-300">
                    <path d="m6 9 6 6 6-6"></path>
                </svg>
            </div>

            <div class="htmx-indicator absolute inset-0 flex items-center justify-center">
                <svg class="animate-spin h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none"
                     viewBox="0 0 24 24">
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                    <path class="opacity-75" fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
            </div>
        </button>
    </div>
{% endif %}